### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by NeonNOXX** [Soufaker/laoyue#1]
![image](https://github.com/Soufaker/laoyue/assets/89446802/60ef6f0f-7638-4390-a0c4-dfd75a895253)
大哥，这个咋整呢，问题出在config.ini上？

**Comment by Soufaker** [comment]
应该是把你config.ini没配置对,编码好像有问题,你拉下来重新配置下呢,最新版本1.03这个应该是可以正常运行的,很多师傅反馈是可以用的,你在试试呢实在不行加我微信uaixhy



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Soufaker/laoyue"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月30日(星期二) 上午10:58
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Soufaker/laoyue] 运行报错 (Issue #1)





 

 大哥，这个咋整呢，问题出在config.ini上？

**Comment by NeonNOXX** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by furyxss** [comment]
cf.read('./config/config.ini',encoding='utf-8')   window下 源码加这个地方不会报错，但是windows  python64位有 dll 加载问题

**Comment by NeonNOXX** [comment]
这是来自QQ邮箱的假期自动回复邮件。 您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by NeonNOXX** [comment]
这是来自QQ邮箱的假期自动回复邮件。 您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
