### ISSUE TITLE
subfinder api配置文件

### ISSUE THREAD

**Issue by brucelsone** [Soufaker/laoyue#12]
subfinder的api密钥直接根据官方模版写到/config/config.ini文件中吗
<img width="1052" alt="image" src="https://github.com/Soufaker/laoyue/assets/101378596/2b3a7df1-7012-4c5c-b0a7-e74b97d08120">

**Comment by Soufaker** [comment]
你用最新得代码

**Comment by Soufaker** [comment]
早上得时候我又跟新了,昨天这个有问题

**Comment by Soufaker** [comment]
![image](https://github.com/Soufaker/laoyue/assets/44189635/a771c897-8ad4-49e1-b577-d7b320353c4c)
这里我修改成这个了,之前有bug,现在修复了

**Comment by Soufaker** [comment]
最好拉现在的代码哈
