### ISSUE TITLE
如何被动扫描

### ISSUE THREAD

**Issue by ZhangHaiShen** [Soufaker/laoyue#13]
![7221c8207b4c34137248e85cfb0e2ea](https://github.com/Soufaker/laoyue/assets/103837881/13bed0dd-0143-4ada-a566-5ee843f8ded8)

**Comment by Soufaker** [comment]
这个被动扫描指的是你自己收集的IP和URL资产拿去扫,不需要通过前面的自动化收集资产,然后资产的话你自己放在./result/notautolist/notautolist.txt里在使用这个命令
