### ISSUE TITLE
subfinder配置文件

### ISSUE THREAD

**Issue by brucelsone** [Soufaker/laoyue#15]
没有subfinder配置文件，无法添加api增加子域名获取

**Comment by Soufaker** [comment]
默认配置在/root/.config/subfinder/provider-config.yaml 可以配置api

**Comment by Soufaker** [comment]
你要是需要我下个版本把他放到config文件里。。

**Comment by Soufaker** [comment]
![image](https://github.com/Soufaker/laoyue/assets/44189635/71f4890b-f6c9-4e74-ae1c-16f28518cddf)

**Comment by Soufaker** [comment]
你是不是python版本低导致的哦,我py3.9是正常运行的

**Comment by Soufaker** [comment]
可以公众号我的laoyue安装文章安装一下3.9应该很快就解决了

**Comment by Soufaker** [comment]
下个版本我改下代码兼容下3.6试试你先提升个版本呢

**Comment by Soufaker** [comment]
更新了3.6版本适配的laoyue.py,可以试试,这个问题应该可以解决
