### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'capture_output'

### ISSUE THREAD

**Issue by ZSC0810** [Soufaker/laoyue#16]
开启subfinder子域名扫描
Scanning domain: xxx.com
Traceback (most recent call last):
  File "laoyue.py", line 1398, in <module>
    get_all_url_fo_yt()
  File "laoyue.py", line 368, in get_all_url_fo_yt
    run_subfinder(all_qc_domain_list)
  File "laoyue.py", line 426, in run_subfinder
    result = subprocess.run(["./inifile/subfinder/subfinder", "-all","-d", domain], capture_output=True, text=True)
  File "/usr/lib64/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'

**Comment by Soufaker** [comment]
你的python版本低了,安装3.9试试

**Comment by ZSC0810** [comment]
我是安装的3.9 安装公众号 一步步做的。。。

**Comment by Soufaker** [comment]
这样吗。。
![image](https://github.com/Soufaker/laoyue/assets/44189635/007c4a05-6663-41ab-ad55-86f1f07db9d9)
你这里报错提示你现在yo用的是python3.6的库额

**Comment by ZSC0810** [comment]
好嘞  我再试试

**Comment by ZSC0810** [comment]
感谢 大佬 已经可以正常工作了。扫到漏洞，来报喜~~~
