### ISSUE TITLE
1.2.4最新版报错

### ISSUE THREAD

**Issue by xxsmile123** [Soufaker/laoyue#20]
报错信息如下所示：
Traceback (most recent call last):
  File "/home/kali/tools/laoyue/laoyue.py", line 1404, in <module>
    quchong_list, mgwj_list, ld_list, fs_list, host_scan_list = quchong_info_list(all_info_list)
                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/tools/laoyue/laoyue.py", line 651, in quchong_info_list
    ld_list = nuclei(file_filter_name)
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/tools/laoyue/laoyue.py", line 1121, in nuclei
    temp.append(x[2])
                ~^^^
IndexError: list index out of range

**Comment by Soufaker** [comment]
这里我做了异常的
![image](https://github.com/Soufaker/laoyue/assets/44189635/70cc3308-1859-4586-bdd9-978d9d3f21dc)

**Comment by Soufaker** [comment]
你重新拉一下代码呢,好像之前我修复过这个

**Comment by xxsmile123** [comment]
> 这个问题是因为之前nuclei更新后,导出的结果和之前不一样或有html代码,然后之前的代码没在异常就会报错

我重新拉一下试试吧。这里有个建议，更新nuclei的时候由于网络存在差异，可能会更新失败，建议做提醒不要直接更。比如运行次数超过10次或者20次，进行信息输出。

**Comment by Soufaker** [comment]
好的,之后加上这点

**Comment by Soufaker** [comment]
这个nuclei代码确实有问题,我今天看了下nuclei最新版本输出结果用之前的代码不行,需要用下面的,你可以修改一下
def nuclei(filename):
    os.system('./inifile/lousao/nuclei -update')
    os.system('./inifile/lousao/nuclei -update-templates ')
    loud_file = './result/loudong/' + time.strftime("%Y-%m-%d-%H-%M-%S", time.localtime()) + 'ld_scan.txt'
    # os.system('./inifile/lousao/nuclei -un -ut')
    os.system('./inifile/lousao/nuclei -mhe 3 -timeout 1 -rl 30000 -c 10000  -s medium,high,critical -l ' + str(
        filename) + ' -o ' + str(loud_file))
    result = []
    valid_keywords = ['info', 'low', 'high', 'critical']
    result_list = open('tt.txt', 'r', encoding='utf-8').read().split('\n')
    # 解析每一行
    for line in result_list:
        info = []
        # 检查行的开头
        if line.startswith('[') and any(keyword in line for keyword in valid_keywords):
            info.append(line.split(' ')[0])
            info.append(line.split(' ')[2])
            info.append(line.split(' ')[3])
            result.append(info)


    return result

**Comment by Soufaker** [comment]
`def nuclei(filename):
    os.system('./inifile/lousao/nuclei -update')
    os.system('./inifile/lousao/nuclei -update-templates ')
    loud_file = './result/loudong/' + time.strftime("%Y-%m-%d-%H-%M-%S", time.localtime()) + 'ld_scan.txt'
    # os.system('./inifile/lousao/nuclei -un -ut')
    os.system('./inifile/lousao/nuclei -mhe 3 -timeout 1 -rl 30000 -c 10000  -s medium,high,critical -l ' + str(
        filename) + ' -o ' + str(loud_file))
    result = []
    valid_keywords = ['info', 'low', 'high', 'critical']
    result_list = open('tt.txt', 'r', encoding='utf-8').read().split('\n')
    # 解析每一行
    for line in result_list:
        info = []
        # 检查行的开头
        if line.startswith('[') and any(keyword in line for keyword in valid_keywords):
            info.append(line.split(' ')[0])
            info.append(line.split(' ')[2])
            info.append(line.split(' ')[3])
            result.append(info)

    return result`

**Comment by Soufaker** [comment]
自动更新你可以自己收到注释一下,我会在下个版本更新更多功能以及优化,你先用着吧

**Comment by xxsmile123** [comment]
> 自动更新你可以自己收到注释一下,我会在下个版本更新更多功能以及优化,你先用着吧

感谢师傅解答，我自己会多注意的。
