### ISSUE TITLE
xxx查需要开会员吗？

### ISSUE THREAD

**Issue by A-dmins** [Soufaker/laoyue#3]
xxx查需要开会员吗？

**Comment by A-dmins** [comment]
一直卡在着是因为被ban了？还是因为没开会员？
![1689131836361](https://github.com/Soufaker/laoyue/assets/62530743/25ac1e4b-a751-43e8-998c-5bfe9805f13b)

**Comment by Soufaker** [comment]
这个功能暂时阉割了,没在使用调试了,因为有更好的域名手机,你可以用狼组的enscan,比较好用
