### ISSUE TITLE
运行卡住

### ISSUE THREAD

**Issue by xiaobaibai12** [Soufaker/laoyue#4]
![image](https://github.com/Soufaker/laoyue/assets/47846097/1f624605-eb0a-4a60-afc2-cec34c51c1d9)
请问运行后一直卡在这里是什么情况啊，各项配置都配置好了到底

**Comment by Soufaker** [comment]
使用python3.7和centos7环境

**Comment by Soufaker** [comment]
SRC.txt里的域名你改成XXX.com呢,别加https://www这个就跑主域名

**Comment by xiaobaibai12** [comment]
> SRC.txt里的域名你改成XXX.com呢,别加[https://www这个就跑主域名](https://www%E8%BF%99%E4%B8%AA%E5%B0%B1%E8%B7%91%E4%B8%BB%E5%9F%9F%E5%90%8D)

感谢，忘记了是跑主域名来着。

**Comment by xiaobaibai12** [comment]
有交流群之类的吗
