### ISSUE TITLE
提个小建议

### ISSUE THREAD

**Issue by york-cmd** [Soufaker/laoyue#5]
是否可以加一个不使用-n参数，只跑src.txt里的子域名信息 ，不进行收集。  因fofa存在bug ，
比如域名：domain="testphp.vulnweb.com"   fofa会自动换成host="testphp.vulnweb.com" ,出现的问题如下
<img width="1619" alt="image" src="https://github.com/Soufaker/laoyue/assets/64241747/2b0364e8-ed71-4e30-a8fb-9dff15ca2ca6">

<img width="1039" alt="image" src="https://github.com/Soufaker/laoyue/assets/64241747/b684f95a-0564-4f39-9523-f47c6bc763fe">

导致有很多偏离的目标，浪费了大量的时间。

**Comment by Soufaker** [comment]
好的,这个域名便宜我收集后过滤处理一下就行了

**Comment by Soufaker** [comment]
![{I50V_U${2~3S_@NWL{{Y0T](https://github.com/Soufaker/laoyue/assets/44189635/89c7626d-e816-4a1d-9eae-4b73cd4cd2e9)
这种情况我这样处理一下就好了 不在收集的子域名列表里跳过不收集

**Comment by york-cmd** [comment]
是否可以加多个awvs扫描， 假如有4个awvs服务器   ，目标数为2000个 平均每个服务器添加500个进去。

**Comment by Soufaker** [comment]
我那个awvs可以单独使用,这个应该不难,你可以自己魔改下那个脚本
