### ISSUE TITLE
鹰图调用提示：出异常了 list index out of range

### ISSUE THREAD

**Issue by xiaobaibai12** [Soufaker/laoyue#7]
请问在运行时nohup.out文件中鹰图出现 list index out of range是什么情况啊
![image](https://github.com/Soufaker/laoyue/assets/47846097/bf1350b6-6d2a-4bf5-aa44-f70049309654)

**Comment by Soufaker** [comment]
curl检查下api地址是否能获取地址,如果不能应该是被封IP了,建议使用国外vps,国内容易被封
