### ISSUE TITLE
鹰图请求返回{"code":40201,"data":null,"message":"涉及灰色资产，不支持查询"}

### ISSUE THREAD

**Issue by xiaobaibai12** [Soufaker/laoyue#8]
![image](https://github.com/Soufaker/laoyue/assets/47846097/119bf95c-5e59-4ad3-993b-03e1e553a76e)

**Comment by Soufaker** [comment]
这个估计是你搜索的资产有问题,灰色资产。。。搜不到,我这里加一个报错异常处理一下这个报错把
