### ISSUE TITLE
大佬....还是之前灰色资产的问题

### ISSUE THREAD

**Issue by xiaobaibai12** [Soufaker/laoyue#9]
上个版本因为用的yingtu去搜集国外H1和BC的资产，导致有的资产yingtu会识别为灰色资产，原因不知.....
18版本这个，我看代码部分是返回40201就切换下一个yingtuAPI哇，导致了如果5个查询域名中带有灰色资产，就会报所有API积分都用完了。
![image](https://github.com/Soufaker/laoyue/assets/47846097/ae7b8627-bd68-4bfb-acf8-a31952e5ddd3)

**Comment by xiaobaibai12** [comment]
小小的建议：能否在config中可设置鹰图一次查询域名数量为1个，然后查询到返回40201则跳过当前域名，继续下一个。大佬幸苦0.0

**Comment by Soufaker** [comment]
好的没问题,因为之前是感觉跑太慢了,默认绑定5个域名以上一起收集,不过可能要等明天了,今天很忙哈哈,改好了你在试试




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Soufaker/laoyue"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月22日(星期三) 中午11:29
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [Soufaker/laoyue] 大佬....还是之前灰色资产的问题 (Issue #9)





 
小小的建议：能否在config中可设置鹰图一次查询域名数量为1个，然后查询到返回40201则跳过当前域名，继续下一个。大佬幸苦0.0

**Comment by Soufaker** [comment]
好了你用最小的1.19就可以配置了
